const crypto=require('node:crypto');
const {test,expect}=require('@playwright/test');
test.beforeEach(async({context})=>{
  await context.addInitScript(()=>{if(!localStorage.getItem('gp-last-visit-v1'))localStorage.setItem('gp-last-visit-v1',JSON.stringify({mode:'demo',projectId:''}));});
});
test('browser workflow: edit prices, commit demo, copy, create and isolate project drafts',async({page})=>{
  const pair=crypto.generateKeyPairSync('rsa',{modulusLength:2048});
  const fixture={type:'service_account',client_email:'ui-test@example.iam.gserviceaccount.com',private_key:pair.privateKey.export({type:'pkcs8',format:'pem'})};
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.locator('#total')).toHaveText('3');
  await page.screenshot({path:'data/ui-home.png',fullPage:true});
  await page.getByRole('checkbox',{name:'选择 coins_100',exact:true}).check();
  await page.getByRole('button',{name:'批量改价',exact:true}).click();
  await page.locator('#priceKind').selectOption('percent');
  await page.locator('#priceValue').fill('10');
  await page.locator('#priceRegions [data-clear]').click();
  await page.locator('#priceRegions input[value="US"]').check();
  await page.getByRole('button',{name:'计算并应用到草稿'}).click();
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  await expect(page.locator('tr').filter({has:page.locator('[data-select="coins_100"]')})).toContainText('1.09');
  await expect(page.locator('tr').filter({has:page.locator('[data-select="coins_100"]')})).toContainText('HKD 7');
  await page.locator('#preview').click();
  await expect(page.locator('#dialogBody')).toContainText('USD 0.99');
  await expect(page.locator('#dialogBody')).toContainText('USD 1.09');
  await expect(page.locator('#dialogBody')).not.toContainText('HKD');
  expect(await page.locator('.diff-table td').first().evaluate(el=>el.getBoundingClientRect().width)).toBeGreaterThan(250);
  await page.screenshot({path:'data/ui-preview.png',fullPage:true});
  await page.locator('#confirmWrite').check();
  await page.getByRole('button',{name:'提交演示变更'}).click();
  await expect(page.locator('#dialogTitle')).toHaveText('提交结果');
  await expect(page.locator('#dialogBody')).toContainText('已核对');
  await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  await expect(page.locator('#dirtyCount')).toHaveText('0');
  await page.getByRole('checkbox',{name:'选择 coins_100',exact:true}).check();
  await page.locator('#copy').click();await page.locator('#copyIds').fill('coins_200\ncoins_300');
  await page.getByRole('button',{name:'生成商品草稿'}).click();
  await expect(page.locator('#total')).toHaveText('5');
  await expect(page.locator('#dirtyCount')).toHaveText('2');
  await page.reload();await expect(page.locator('#dirtyCount')).toHaveText('2');
  await page.locator('#newProject').click();
  await expect(page.locator('#dialogTitle')).toHaveText('新建项目');
  await page.locator('#profileName').fill('测试项目 A');
  await page.locator('#profilePackage').fill('com.example.appa');
  await page.locator('#credentialFile').setInputFiles({name:'test-service-account.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});
  // Simulate a tab retaining the session token from before a server restart.
  await page.evaluate(()=>{token='expired-before-restart';});
  await page.getByRole('button',{name:/^(保存|创建)并切换到此项目$/}).click();
  await expect(page.locator('#package')).toHaveText('com.example.appa');
  await expect(page.locator('#total')).toHaveText('0');
  await page.locator('#settings').click();
  await expect(page.locator('#credentialStatus')).toContainText(fixture.client_email);
  await expect(page.locator('#credentialJson')).toHaveValue('');
  await page.getByText('如何准备 Google 授权？（完整步骤）',{exact:true}).click();
  await expect(page.locator('.auth-guide')).toContainText('管理商店发布信息');
  await page.getByText('或直接粘贴 JSON 内容',{exact:true}).click();
  fixture.client_email='ui-replacement@example.iam.gserviceaccount.com';
  await page.locator('#credentialJson').fill(JSON.stringify(fixture));
  await page.getByRole('button',{name:/^(保存|创建)并切换到此项目$/}).click();
  await page.locator('#settings').click();
  await expect(page.locator('#credentialStatus')).toContainText(fixture.client_email);
  await expect(page.locator('#credentialJson')).toHaveValue('');
  await page.screenshot({path:'data/ui-credentials.png',fullPage:true});
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.locator('#create').click();
  await page.locator('#editId').fill('project_a_only');
  await page.getByRole('textbox',{name:'商品名称',exact:true}).fill('A 项目商品');
  await page.getByRole('textbox',{name:'商品描述',exact:true}).fill('仅用于本地草稿验证');
  await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  await page.locator('#settings').click();
  await page.locator('#addProject').click();
  await expect(page.locator('#dialogTitle')).toHaveText('新建项目');
  await expect(page.locator('#profileName')).toHaveValue('');
  await expect(page.locator('#profilePackage')).toHaveValue('');
  await expect(page.locator('#credentialStatus')).toContainText('尚未配置');
  await page.locator('#profileName').fill('测试项目 B');
  await page.locator('#profilePackage').fill('com.example.appb');
  await page.getByRole('button',{name:/^(保存|创建)并切换到此项目$/}).click();
  await expect(page.locator('#package')).toHaveText('com.example.appb');
  await expect(page.locator('#project option')).toHaveCount(2);
  await expect(page.locator('#total')).toHaveText('0');
  await page.locator('#project').selectOption({label:'测试项目 A'});
  await expect(page.locator('#total')).toHaveText('1');
  await expect(page.locator('#products')).toContainText('project_a_only');
  await page.reload();
  await expect(page.locator('#mode')).toHaveValue('live');
  await expect(page.locator('#package')).toHaveText('com.example.appa');
  await expect(page.locator('#products')).toContainText('project_a_only');
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  const secondTab=await page.context().newPage();
  await secondTab.goto('/');
  await expect(secondTab.locator('#package')).toHaveText('com.example.appa');
  await expect(secondTab.locator('#products')).toContainText('project_a_only');
  await secondTab.close();
  await page.locator('#mode').selectOption('demo');
  await expect(page.locator('#total')).toHaveText('5');
  await expect(page.locator('#dirtyCount')).toHaveText('2');
  await page.reload();
  await expect(page.locator('#mode')).toHaveValue('demo');
  await expect(page.locator('#total')).toHaveText('5');
  await expect(page.locator('#dirtyCount')).toHaveText('2');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'data/ui-mobile.png',fullPage:true});
  expect(errors).toEqual([]);
});

test('preview immediately shows progress, then displays disabled API error above the fold without losing drafts',async({page})=>{
  await page.goto('/');
  await expect(page.locator('#total')).toHaveText('3');
  await page.locator('#preview').click();
  await expect(page.locator('#dialogTitle')).toHaveText('操作未完成');
  await expect(page.locator('#dialogBody')).toContainText('没有待提交变化');
  await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  await page.getByRole('checkbox',{name:'选择 coins_100',exact:true}).check();
  await page.locator('#price').click();
  await page.locator('#priceValue').fill('8.99');
  await page.locator('#priceRegions [data-clear]').click();
  await page.locator('#priceRegions input[value="US"]').check();
  await page.getByRole('button',{name:'计算并应用到草稿'}).click();
  let release;
  const gate=new Promise(r=>release=r);
  await page.route('**/api/preview',async route=>{
    await gate;
    await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'Google 403：Google Play Android Developer API has not been used in project 123456789012 before or it is disabled.'})});
  });
  await page.locator('#preview').click();
  await expect(page.locator('#dialogTitle')).toHaveText('正在生成预览');
  await expect(page.locator('.preview-loading')).toBeVisible();
  release();
  await expect(page.locator('#dialogTitle')).toHaveText('无法生成预览');
  await expect(page.locator('#dialogBody')).toContainText('123456789012');
  await expect(page.getByRole('link',{name:'打开 Google API 设置 ↗'})).toHaveAttribute('href','https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com?project=123456789012');
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  await page.screenshot({path:'data/ui-api-error.png',fullPage:true});
  await page.getByRole('button',{name:'返回编辑',exact:true}).click();
  await expect(page.locator('#preview')).toBeEnabled();
});

test('all-region conversion adds missing countries and preserves option settings until user applies draft',async({page})=>{
  await page.goto('/');
  await expect(page.locator('#total')).toHaveText('3');
  await page.getByRole('checkbox',{name:'选择 coins_100',exact:true}).check();
  await page.route('**/api/convert',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({
    regionVersion:{version:'2025/03'},convertedRegionPrices:{
      US:{regionCode:'US',price:{currencyCode:'USD',units:'2',nanos:0}},
      HK:{regionCode:'HK',price:{currencyCode:'HKD',units:'16',nanos:0}},
      JP:{regionCode:'JP',price:{currencyCode:'JPY',units:'300',nanos:0}}
    }
  })}));
  await page.locator('#price').click();
  await page.locator('#priceKind').selectOption('convert');
  await page.locator('#regionScope').selectOption('all');
  await expect(page.locator('#priceRegions input[type=search]')).toBeDisabled();
  await page.locator('#priceValue').fill('2');
  await page.locator('#priceOption').selectOption('buy');
  await page.getByRole('button',{name:'计算并应用到草稿'}).click();
  await expect(page.locator('#dialogTitle')).toHaveText('Google 换算结果');
  await expect(page.locator('#dialogBody')).toContainText('JP');
  await expect(page.locator('#dialogBody')).toContainText('新增地区');
  await expect(page.locator('#dirtyCount')).toHaveText('0');
  await page.getByRole('button',{name:'应用到草稿',exact:true}).click();
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  await page.locator('[data-edit="coins_100"]').click();
  await expect(page.locator('[data-k="regionCode"]')).toHaveCount(3);
  await expect(page.locator('[data-k="regionCode"]').nth(2)).toHaveValue('JP');
  await expect(page.locator('[data-legacy="0"]')).toBeChecked();
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.locator('#preview').click();
  await expect(page.locator('#dialogTitle')).toContainText('提交前预览');
  await expect(page.locator('#dialogBody')).toContainText('JP');
});

test('multilingual template download and upload preview preserves prices and existing languages',async({page})=>{
  await page.goto('/');
  await expect(page.locator('#total')).toHaveText('3');
  await page.getByRole('checkbox',{name:'选择 coins_100',exact:true}).check();
  await page.locator('#languages').click();
  const downloadEvent=page.waitForEvent('download');
  await page.locator('#templateLanguages input[type=search]').fill('zh-TW');
  await page.locator('#templateLanguages input[value="zh-TW"]').check();
  await page.locator('#templateLanguages input[type=search]').fill('日语');
  await page.locator('#templateLanguages input[value="ja-JP"]').check();
  await expect(page.locator('#templateLanguages .choice-summary')).toContainText('已选 2 项');
  await page.locator('#templateLanguages input[type=search]').fill('');
  await expect(page.locator('#templateLanguages input[value="zh-TW"]')).toBeChecked();
  await page.screenshot({path:'data/ui-language-options.png',fullPage:true});
  await page.locator('#downloadLanguages').click();
  const download=await downloadEvent;
  expect(download.suggestedFilename()).toBe('gp-multilingual-template.csv');
  const stream=await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);
  const csv=Buffer.concat(chunks).toString('utf8');expect(csv).toContain('zh-TW');expect(csv).toContain('ja-JP');
  await page.locator('#templateLanguages [data-clear]').click();
  await expect(page.locator('#templateLanguages .choice-summary')).toHaveText('已选 0 项');
  await page.locator('#languageFile').setInputFiles({name:'languages.csv',mimeType:'text/csv',buffer:Buffer.from('productId,languageCode,title,description\r\ncoins_100,zh-TW,100金幣,購買後獲得100金幣')});
  await page.getByRole('button',{name:'检查并预览导入'}).click();
  await expect(page.locator('#dialogTitle')).toContainText('多语言导入预览');
  await expect(page.locator('#dialogBody')).toContainText('新增语言');
  await expect(page.locator('#dirtyCount')).toHaveText('0');
  await page.getByRole('button',{name:'应用到草稿',exact:true}).click();
  await page.locator('[data-edit="coins_100"]').click();
  await expect(page.locator('[data-k="languageCode"]')).toHaveCount(3);
  await expect(page.locator('[data-k="languageCode"]').last()).toHaveValue('zh-TW');
  await expect(page.locator('[data-k="price"]')).toHaveCount(2);
  await page.getByRole('button',{name:'取消',exact:true}).click();
  await page.locator('#preview').click();
  await expect(page.locator('#dialogTitle')).toContainText('提交前预览');
  await expect(page.locator('#dialogBody')).toContainText('zh-TW');
  await expect(page.locator('.diff-table')).not.toContainText('购买选项');
});

test('selection controls save language and regional price changes',async({page})=>{
  await page.goto('/');await expect(page.locator('#total')).toHaveText('3');
  await page.locator('[data-edit="coins_100"]').click();
  await page.locator('#addLocale').click();
  await page.locator('select[data-k="languageCode"]').last().selectOption('ja-JP');
  await page.locator('[data-k="title"]').last().fill('100コイン');
  await page.locator('[data-k="description"]').last().fill('100コインを獲得');
  await page.locator('[data-add-r="0"]').click();
  await page.locator('select[data-k="regionCode"]').last().selectOption('JP');
  await page.locator('select[data-k="currencyCode"]').last().selectOption('JPY');
  await page.locator('[data-k="price"]').last().fill('150');
  await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  await expect(page.locator('#modal')).not.toBeVisible();
  await page.locator('[data-edit="coins_100"]').click();
  await expect(page.locator('select[data-k="languageCode"]').last()).toHaveValue('ja-JP');
  await expect(page.locator('select[data-k="regionCode"]').last()).toHaveValue('JP');
  await expect(page.locator('select[data-k="currencyCode"]').last()).toHaveValue('JPY');
  await expect(page.locator('[data-k="price"]').last()).toHaveValue('150');
  await page.screenshot({path:'data/ui-edit-options.png',fullPage:true});
});

test('catalog filters retain explicit selection scope and region search preserves hidden values',async({page})=>{
  await page.goto('/');await expect(page.locator('#total')).toHaveText('3');
  await expect(page.locator('#price')).toBeDisabled();
  await page.locator('[data-select="coins_100"]').check();
  await page.locator('#search').fill('REMOVE_ADS');
  await expect(page.locator('#resultCount')).toHaveText('显示 1 / 3 个商品');
  await expect(page.locator('#selectionHint')).toContainText('筛选外 1 个');
  await page.locator('#selectAll').check();
  await expect(page.locator('#selectedCount')).toHaveText('2');
  await expect(page.locator('#copy')).toBeDisabled();
  await page.locator('#resetFilters').click();
  await page.locator('[data-filter="selected"]').click();
  await expect(page.locator('#products tr')).toHaveCount(2);
  await page.locator('#clearSelection').click();
  await expect(page.locator('#empty')).toContainText('没有匹配的商品');
  await page.locator('#resetFilters').click();
  await page.locator('[data-edit="coins_100"]').click();
  await page.locator('[data-region-search="0"]').fill('美元');
  await expect(page.locator('.region-row:visible')).toHaveCount(1);
  await page.locator('[data-k="price"]').first().fill('1.99');
  await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  await page.locator('[data-filter="dirty"]').click();
  await expect(page.locator('#products tr')).toHaveCount(1);
  await expect(page.locator('#products')).toContainText('HKD 7');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'data/ui-polished-mobile.png',fullPage:true});
});

test('single product template preserves unsaved edits and returns to editor before saving',async({page})=>{
  await page.goto('/');await expect(page.locator('#total')).toHaveText('3');
  await page.locator('[data-select="coins_550"]').check();
  await page.locator('[data-edit="coins_100"]').click();
  await page.locator('[data-k="price"]').first().fill('3.99');
  await page.locator('#editLanguages').click();
  await expect(page.locator('#dialogBody')).toContainText('当前编辑商品 coins_100');
  const downloadEvent=page.waitForEvent('download');
  await page.locator('#downloadLanguages').click();
  const download=await downloadEvent;const stream=await download.createReadStream();const chunks=[];
  for await(const chunk of stream)chunks.push(chunk);
  const csv=Buffer.concat(chunks).toString('utf8');expect(csv).toContain('coins_100');expect(csv).not.toContain('coins_550');
  await page.keyboard.press('Escape');
  await expect(page.locator('#editId')).toHaveValue('coins_100');
  await expect(page.locator('[data-k="price"]').first()).toHaveValue('3.99');
  await page.locator('#editLanguages').click();
  await page.locator('#languageFile').setInputFiles({name:'single.csv',mimeType:'text/csv',buffer:Buffer.from('productId,languageCode,title,description\ncoins_100,ja-JP,100コイン,100コインを獲得')});
  await page.getByRole('button',{name:'检查并预览导入'}).click();
  await expect(page.locator('#dialogTitle')).toContainText('多语言导入预览');
  await page.getByRole('button',{name:'应用到商品表单'}).click();
  await expect(page.locator('[data-k="languageCode"]').last()).toHaveValue('ja-JP');
  await expect(page.locator('[data-k="price"]').first()).toHaveValue('3.99');
  await expect(page.locator('#dirtyCount')).toHaveText('0');
  await page.getByRole('button',{name:'保存草稿',exact:true}).click();
  await expect(page.locator('#dirtyCount')).toHaveText('1');
  await page.locator('[data-edit="coins_550"]').click();
  await expect(page.locator('[data-k="languageCode"]')).toHaveCount(2);
});
